---
# tasks file for Ubuntu
- name: eclipse | Ensure installed OpenJDK
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: eclipse | Make a temporary directory.
  tempfile:
    state: directory
  register: directory

- name: eclipse | Download files
  get_url:
    url: https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2019-03/R/eclipse-inst-linux64.tar.gz&mirror_id=1248
    dest: "{{ directory.path }}"
  become: no
  when: ansible_distribution_major_version == "18"
  environment: "{{ proxy_env }}"

- name: eclipse | Extract tar.gz file
  unarchive:
    src: "{{ directory.path }}/eclipse-inst-linux64.tar.gz"
    dest: "{{ directory.path }}"


