---
# tasks file for Ubuntu
- name: vscode | Get GPG key
  shell: |
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
    sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  become: yes
  environment: "{{ proxy_env }}"

- name: vscode | Ensure installing apt-transport-https
  apt:
    name: apt-transport-https
    state: latest
    update_cache: no
  become: yes
  environment: "{{ proxy_env }}"

- name: vscode | Ensure existing code.
  apt:
    name: code
    state: latest
    update_cache: yes
  become: yes
  environment: "{{ proxy_env }}"

- name: vscode | Install extensions.
  shell: |
    code --install-extension vscodevim.vim
    code --install-extension ms-vscode.PowerShell
    code --install-extension EditorConfig.EditorConfig
    code --install-extension esbenp.prettier-vscode
    code --install-extension CoenraadS.bracket-pair-colorizer
    code --install-extension christian-kohler.path-intellisense
    code --install-extension aaron-bond.better-comments
    code --install-extension eamodio.gitlens
    code --install-extension donjayamanne.githistory
    code --install-extension piotrpalarz.vscode-gitignore-generator
    code --install-extension VisualStudioExptTeam.vscodeintellicode
    code --install-extension ritwickdey.LiveServer
    code --install-extension Orta.vscode-jest
    code --install-extension ms-vscode.vscode-typescript-tslint-plugin
    code --install-extension ms-vscode-remote.vscode-remote-extensionpack
    code --install-extension ms-vscode-remote.remote-ssh-edit
  environment: "{{ proxy_env }}"

