---
# tasks file for rbenv
- name: nodejs | Check if installing nodejs
  shell: which nodejs
  register: nodejs_installed
  ignore_errors: yes

- name: nodejs | Install tasks for Ubunts
  include: ubuntu.yaml
  when:
    - nodejs_installed.stdout == ""
    - ansible_distribution == "Ubuntu"

