---
# tasks for Ubuntu
- name: OCaml | Ensure camlp5 installed.
  shell: opam install camlp5
  environment: "{{ proxy_env }}"

- name: OCaml | Ensure conf-m4 installed.
  shell: opam install conf-m4
  environment: "{{ proxy_env }}"

- name: OCaml | Ensure ocamlfind installed.
  shell: opam install ocamlfind
  environment: "{{ proxy_env }}"

- name: OCaml | Ensure num installed.
  shell: opam install num
  environment: "{{ proxy_env }}"
