---
# tasks for coq
- name: coq | Add Coq repository.
  shell: opam repo add coq-released https://coq.inria.fr/opam/released
  environment: "{{ proxy_env }}"

- name: coq | Install tasks for Ubuntu
  include: ubuntu.yaml
  when:
    - ansible_distribution == "Ubuntu"
