---
# tasks file for Ubuntu
- name: llvm | Ensure installed llvm (APT)
  apt:
    name: llvm
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: llvm | Ensure installed llvm-runtime (APT)
  apt:
    name: llvm-runtime
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: llvm | Ensure installed clang (APT)
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  environment: "{{ proxy_env }}"
  with_items:
    - clang
    - clang-format
    - clang-tidy
    - clang-tools
    - lldb
    - cmake
    - cmake-curses-gui
    - cmake-data
    - cmake-doc
    - cmake-extras
    - libc++-dev

- name: llvm | Create Symbolic link to lldb
  file:
    src: /usr/bin/lldb-server-6.0
    dest: /usr/bin/lldb-server-6.0.0
    state: link
  become: yes
