---
# tasks file for Ubuntu
- name: docker | Uninstall old version. (APT)
  apt:
    name: [ "docker", "docker-engine", "docker.io" ]
    state: absent
  become: yes
  environment: "{{ proxy_env }}"

- name: docker | Ensure installing packages. (APT)
  apt:
    name: [ "apt-transport-https", "ca-certificates", "curl", "software-properties-common" ]
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: docker | Ensure to register gpg key. (APT)
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: docker | Ensure existing apt repository. (APT)
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: yes

- name: docker | Update repository. (APT)
  apt:
    update_cache: yes
  become: yes
  environment: "{{ proxy_env }}"

- name: docker | Ensure installing docker-ce (APT)
  apt:
    name: docker-ce
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: docker | Ensur installing docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: yes
  environment: "{{ proxy_env }}"

- name: docker | Ensure user joins group Docker.
  user:
    name: "{{ ansible_user }}"
    append: yes
    group: docker
  become: yes

