---
# tasks for Ubuntu
- name:
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  environment: "{{ proxy_env }}"
  with_items:
    - make
    - m4
    - gcc
    - bubblewrap

- name: opam | Initialize opam.
  shell: opam init

- name: opam | Add script to .bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      eval "$(opam env)"
    marker: "#{mark} ANSIBLE MANAGED BLOCK - opam"
  become: no
